name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: Check, Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run Cargo Tests
        run: cargo test --all-targets --verbose

      - name: Run Cargo Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Cargo Fmt Check
        run: cargo fmt --check

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run Nix Flake Check
        run: nix flake check

      - name: Build Flaker package
        run: nix build --no-link
